services:
  agent2_ticket:
    build: .
    container_name: agent2_ticket
    ports:
      - "8002:8000"
    networks:
      - ai_network
    environment:
      - COLLECTION=agent2_tickets
      - EMBEDDING_MODEL=nomic-embed-text
      - EMBEDDING_DIM=768
      - FORCE_RECREATE_COLLECTION=true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  ai_network:
    external: true
