services:
  agent2_ticket:
    build: .
    container_name: agent2_ticket_testing
    ports:
      - "8002:8000"
    networks:
      - ai_network
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      MODEL_NAME: "${MODEL_NAME}"
      CLASSIFYING_MODEL_NAME: "${CLASSIFYING_MODEL_NAME}"
      EMBEDING_MODEL_NAME: "${EMBEDING_MODEL_NAME}"
      DEBUG: "${DEBUG}"
      SIDEBAR: "${SIDEBAR}"
    volumes:
      - ./documents/knowledge:/app/documents/knowledge
      - ./documents/logs:/app/documents/logs
      - ./documents/processed:/app/documents/processed
      - ./documents/uploads:/app/documents/uploads

networks:
  ai_network:
    external: true
