services:
  agent2_ticket:
    build: .
    container_name: agent2_ticket_testing
    ports:
      - "8006:8000"
    networks:
      - ai_network
    env_file:
      - .env
    volumes:
      - ./documents/knowledge:/app/documents/knowledge
      - ./documents/logs:/app/documents/logs
      - ./documents/processed:/app/documents/processed
      - ./documents/uploads:/app/documents/uploads

networks:
  ai_network:
    external: true