services:
  agent2_ticket:
    build: .
    container_name: agent2_ticket_testing
    ports:
      - "8006:8000"
    networks:
      - ai_network
    environment:
      - COLLECTION=agent2_tickets
      - EMBEDDING_MODEL=mxbai-embed-large
      - EMBEDDING_DIM=1024
      - FORCE_RECREATE_COLLECTION=false
      - AUTO_INDEX_ON_STARTUP=false

networks:
  ai_network:
    external: true
