services:
  agent2_ticket:
    build: .
    container_name: agent2_ticket
    ports:
      - "8002:8000"
    networks:
      - ai_network
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      MODEL_NAME: "${MODEL_NAME}"
      CLASSIFYING_MODEL_NAME: "${CLASSIFYING_MODEL_NAME}"
      EMBEDING_MODEL_NAME: "${EMBEDING_MODEL_NAME}"
      DEBUG: "${DEBUG}"
      SIDEBAR: "${SIDEBAR}"

networks:
  ai_network:
    external: true
