services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      #- ollama_data:/app/data
      - ollama_data:/models
    networks:
      - ai_network
    environment:
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_MODELS=/models
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=["*"]

volumes:
  ollama_data:

networks:
  ai_network:
    external: true
