services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      #- ollama_data:/app/data
      - ollama_data:/models
    networks:
      - ai_network
    environment:
      - OLLAMA_NUM_PARALLEL=8
      - OLLAMA_NUM_THREAD=24
      - OLLAMA_MAX_LOADED_MODELS=4
      - OLLAMA_KEEP_ALIVE=48h
      - OLLAMA_MODELS=/models
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=["*"]

volumes:
  ollama_data:

networks:
  ai_network:
    external: true
